## Example
# files:
#   - name: p1
#     level_path: "../data/test/levels/01.yaml"
#     hrm_path: "../data/test/hrms/01.yaml"
#   - name: p2
#     level_path: "../data/test/levels/02.yaml"
#     hrm_path: "../data/test/hrms/02.yaml"
#   - name: p3
#     level_path: "../data/test/levels/03.yaml"
#     hrm_path: "../data/test/hrms/03.yaml"
#   - name: p4
#     level_path: "../data/test/levels/04.yaml"
#     hrm_path: "../data/test/hrms/04.yaml"
#   - name: p5
#     level_path: "../data/test/levels/05.yaml"
#     hrm_path: "../data/test/hrms/05.yaml"
# OR
# files: "../data/test/" (HRMs and levels must share the same names)
files: ???
level_loading_fn:
  _target_: atlas.envs.xminigrid.level.XMinigridLevel.from_file
  _partial_: true
max_num_rms: ${problem_sampler.hrm_sampler.max_num_rms}
max_num_states: ${problem_sampler.hrm_sampler.max_num_states}
max_num_edges: ${problem_sampler.hrm_sampler.max_num_edges}
max_num_literals: ${problem_sampler.hrm_sampler.max_num_literals}
_target_: atlas.eval_loaders.file.FileEvaluationSetLoader
