num_level_edits: 3
num_hrm_edits: 1
use_move_agent: true
use_add_rm_objs: true
use_add_rm_rooms: true
use_add_rm_transitions: true
use_sparse_reward: true
use_hindsight_level_mutation: false
max_num_args: 2
_target_: atlas.envs.xminigrid.mutators.aggregated.SequentialMutator
